### ISSUE TITLE
Javascript error when clicking on the language switch

### ISSUE THREAD

**Issue by Simsteve7** [FundRequest/website#2]
<img width="391" alt="screen shot 2018-01-26 at 21 38 16" src="https://user-images.githubusercontent.com/1853096/35459635-4c85cde2-02e1-11e8-84a0-8399121b7bd1.png">

First check if $($(this).attr('href')) exists before animating scroll
<img width="463" alt="screen shot 2018-01-26 at 21 25 29" src="https://user-images.githubusercontent.com/1853096/35459611-2f411bb0-02e1-11e8-98e7-3e134019c9b0.png">

**Comment by timdierckxsens** [comment]
Ok if there is multilingual but we should hide it on the site until we have translations. At the moment this is not a priority.

To Do: Hide multilingual from the site

**Comment by timdierckxsens** [comment]
Hide multilingual from the site
