### ISSUE TITLE
As a user I want to see the backing of capital firms on the website

### ISSUE THREAD

**Issue by timdierckxsens** [FundRequest/website#21]
**As Is**

- User is on the website of FundRequest and sees the section "built with" and "Partners"

**To Be**

- User sees a section "Supported By" with the logos of the companies supporting FundRequest
- Possbile image
![screen shot 2018-02-26 at 13 07 41](https://user-images.githubusercontent.com/18101724/36669796-760ac488-1af6-11e8-9cee-b2f61a0becc4.png)

**List of Companies + logo's**

1. Astronaut Capital - to request
2. Hayek Capital - Approved

[hayek capital logo.pdf](https://github.com/FundRequest/website/files/1758461/hayek.capital.logo.pdf)

3. Alpha chain - Approved

![alphachain](https://user-images.githubusercontent.com/18101724/36669347-dc006376-1af4-11e8-9ee2-9fab1d4c2673.jpg)

4. 1kx - to request 
5. Connect Capital -  to request

![connectcapital4](https://user-images.githubusercontent.com/18101724/36669406-1fc0ad5a-1af5-11e8-9c15-ad1b1da52e7b.png)

6. Tetras Capital -  to approve

![cropped-cropped-cropped-cropped-tetras-logo-w-words-black-1](https://user-images.githubusercontent.com/18101724/36669658-f1245612-1af5-11e8-906e-aa22e3394e53.png)

7. Zestads -  to confirm

![1507182988353](https://user-images.githubusercontent.com/18101724/36669610-bd4cca68-1af5-11e8-91c7-12147692c478.png)

**Comment by timdierckxsens** [comment]
@karelstriegel  /  @gerbert-vandenberghe  to review and decide whether we put it in our backlog.

**Comment by gerbert-vandenberghe** [comment]
Zestads logo in psd
[ZestAds - Logo - RGB-01.psd.zip](https://github.com/FundRequest/website/files/1758683/ZestAds.-.Logo.-.RGB-01.psd.zip)
