### ISSUE TITLE
Timeline jumps around when click other month

### ISSUE THREAD

**Issue by Simsteve7** [FundRequest/website#3]
Issues (only for desktop):
- Not very clear that you can click on the different months, and even the years. Maybe make months more visible and add hover effect for the years.
- Timeline jumps around when choosing other month/year and content has a different height. Vertical line also gets bigger / smaller. Maybe align to top and make the vertical line just a bit larger then the timeline or add dots in the beginning and ending.

<img width="1440" alt="screen shot 2018-01-26 at 21 19 54" src="https://user-images.githubusercontent.com/1853096/35459721-a3dd61e0-02e1-11e8-8a63-8f0bd8b9832b.png">
<img width="1440" alt="screen shot 2018-01-26 at 21 20 06" src="https://user-images.githubusercontent.com/1853096/35459722-a3f306f8-02e1-11e8-9d55-e794626e7afe.png">

**Comment by timdierckxsens** [comment]
See comments in Issue #6

**Comment by karelstriegel** [comment]
+ switch from months to quarters

**Comment by Spongobob** [comment]
Continuing in #6
