### ISSUE TITLE
Can not go back when clicking SUBSCRIBE TO NEWSLETTER

### ISSUE THREAD

**Issue by Simsteve7** [FundRequest/website#4]
Mobile:
- On mobile phone it's not possible to close subscription form. (Or not clear for me how to)
<img width="372" alt="screen shot 2018-01-26 at 22 00 20" src="https://user-images.githubusercontent.com/1853096/35460451-5f87a886-02e4-11e8-87eb-170397a93800.png">

Desktop:
- Clicking the gray overlay should also close the subscription form (same as clicking the cross)

**Comment by timdierckxsens** [comment]
I think this is typeform and no longer the website..

**Comment by Simsteve7** [comment]
The typeform is loaded in the website via an iframe. Like you see there is also the websites header on top. There should be a possibility to close the form with one click.
Suggestion: 
- Add a close button on the bottom left (same line-height and size as the green next/previous buttons). This should be an overlay above the iframe.

**Comment by timdierckxsens** [comment]
agreed

**Comment by Spongobob** [comment]
I think these settings come from within typeform ( identical issue on fundrequest.io ). Currently we load the form with their embed plugin. Is there a way i can have access to the form settings?

**Comment by Simsteve7** [comment]
@Spongobob, I found the problem. There is an X to close the form, but it's behind the top banner. Can you up the z-index of the form?

**Comment by Spongobob** [comment]
@Simsteve7 i think we can link this to issue #5.
