### ISSUE TITLE
Showing top banner when scrolling back can be more fluent

### ISSUE THREAD

**Issue by Simsteve7** [FundRequest/website#5]
Showing top banner when scrolling back can be more fluent, add a simple css animation.

**Comment by davyvanroy** [comment]
Should we always show the top banner even when scrolling down?

**Comment by Simsteve7** [comment]
Also an option. My suggestion:
- Desktop: always show top nav, and add a scrollspy 
- Mobile: move top nav to bottom (see https://m.hln.be/). It's easier to click on it when using phone with one hand.

**Comment by timdierckxsens** [comment]
@Simsteve7  and @karelstriegel make final decision

**Comment by karelstriegel** [comment]
I agree with Steve

**Comment by Spongobob** [comment]
Added animation and moved the navbar to the footer on mobile devices.
