### ISSUE TITLE
Alignment of months in timeline seems a bit of on mobile (not centered)

### ISSUE THREAD

**Issue by Simsteve7** [FundRequest/website#6]
<img width="371" alt="screen shot 2018-01-26 at 22 11 23" src="https://user-images.githubusercontent.com/1853096/35461003-3bfb8778-02e6-11e8-8ce5-de34a9e2c758.png">

**Comment by timdierckxsens** [comment]
I would leave out the months and have in the bullets  Q1 - Q2 - Q3 - Q4. Somewhere add 2018. Maybe next to ROADMAP

Also on web when I click on the dots they move up and down (I think it has to do with the timings)

**Comment by timdierckxsens** [comment]
We are not going to do a monthly timeline: @karelstriegel confirm please

**Comment by karelstriegel** [comment]
Change months to quarters

**Comment by Spongobob** [comment]
The movement has to do with the size of the content blocks. If wee don't resize on change there will be white space on smaller slides. Is the actual content available for testing?

**Comment by karelstriegel** [comment]
Not yet
